const superAdminDefaultPermission = {
  name: 'superAdmin',
  isSystemRole: true,
  permissions: [
    'USER_CREATE',
    'USER_READ',
    'USER_UPDATE',
    'USER_DELETE',
    'MENU_CREATE',
    'MENU_READ',
    'MENU_UPDATE',
    'MENU_DELETE',
    'BILLING_CREATE',
    'BILLING_READ',
    'BILLING_UPDATE',
    'BILLING_DELETE',
    'DASHBOARD_READ',
    'REPORTS_CREATE',
    'REPORTS_READ',
    'REPORTS_UPDATE',
    'REPORTS_DELETE',
    'INTEGRATE_PAYMENT_GATEWAY',
    'INTEGRATE_OTHER_PLATFORM',
    'STORE_CREATE',
    'STORE_READ',
    'STORE_UPDATE',
    'STORE_DELETE',
    'DINING_CREATE',
    'DINING_UPDATE',
    'DINING_DELETE',
    'DINING_READ',
    'GRANT_PERMISSION',
    'KITCHEN_CREATE',
    'KITCHEN_DELETE',
    'KITCHEN_UPDATE',
    'KITCHEN_READ',
  ],
};

const defaultRoles = [
  {
    name: 'waiter',
    isSystemRole: true,
    permissions: [
      'DASHBOARD_READ',
      'STORE_READ',
      'MANAGER_ACCESS',
      'DINING_CREATE',
      'DINING_UPDATE',
      'DINING_DELETE',
      'DINING_READ',
      'MENU_CREATE',
      'MENU_READ',
      'MENU_UPDATE',
      'MENU_DELETE',
      'MANAGE_ORDERS',
      'MANAGE_TAKE_ORDERS',
      'MANAGE_LIVE_ORDERS',
      'MANAGE_SETTLEMENT_ORDERS',
      'MANAGE_PREVIOUS_ORDERS',
      'MANAGE_CANCELLED_ORDERS',
      // 'MANAGE_PRE_ORDERS',
    ],
    store: '',
  },
  {
    name: 'kitchen',
    isSystemRole: true,
    permissions: [
      'DASHBOARD_READ',
      'STORE_READ',
      'MANAGER_ACCESS',
      'DINING_CREATE',
      'DINING_UPDATE',
      'DINING_DELETE',
      'DINING_READ',
      'MENU_CREATE',
      'MENU_READ',
      'MENU_UPDATE',
      'MENU_DELETE',
      'MANAGE_ORDERS',
      'MANAGE_TAKE_ORDERS',
      'MANAGE_LIVE_ORDERS',
      'MANAGE_SETTLEMENT_ORDERS',
      'MANAGE_PREVIOUS_ORDERS',
      'MANAGE_CANCELLED_ORDERS',
    ],
    store: '',
  },
  {
    name: 'cashier',
    isSystemRole: true,
    permissions: [
      'DASHBOARD_READ',
      'STORE_READ',
      'MANAGER_ACCESS',
      'DINING_CREATE',
      'DINING_UPDATE',
      'DINING_DELETE',
      'DINING_READ',
      'MENU_CREATE',
      'MENU_READ',
      'MENU_UPDATE',
      'MENU_DELETE',
      'MANAGE_ORDERS',
      'MANAGE_TAKE_ORDERS',
      'MANAGE_LIVE_ORDERS',
      'MANAGE_SETTLEMENT_ORDERS',
      'MANAGE_PREVIOUS_ORDERS',
      'MANAGE_CANCELLED_ORDERS',
    ],
    store: '',
  },
  {
    name: 'storeAdmin',
    isSystemRole: true,
    permissions: [
      'USER_CREATE',
      'USER_READ',
      'USER_UPDATE',
      'USER_DELETE',
      'MENU_CREATE',
      'MENU_READ',
      'MENU_UPDATE',
      'MENU_DELETE',
      'BILLING_CREATE',
      'BILLING_READ',
      'BILLING_UPDATE',
      'BILLING_DELETE',
      'ORDER_CREATE',
      'ORDER_READ',
      'ORDER_UPDATE',
      'ORDER_DELETE',
      'DASHBOARD_READ',
      'REPORTS_CREATE',
      'REPORTS_READ',
      'REPORTS_UPDATE',
      'REPORTS_DELETE',
      'MANAGE_ORDERS',
      'MANAGE_TAKE_ORDERS',
      'MANAGE_LIVE_ORDERS',
      'MANAGE_SETTLEMENT_ORDERS',
      'MANAGE_PREVIOUS_ORDERS',
      'MANAGE_CANCELLED_ORDERS',
      'STORE_READ',
      'STORE_UPDATE',
      'DINING_CREATE',
      'DINING_UPDATE',
      'DINING_DELETE',
      'DINING_READ',
      'MANAGER_ACCESS',
      'KITCHEN_CREATE',
      'KITCHEN_DELETE',
      'KITCHEN_UPDATE',
      'KITCHEN_READ',
    ],
    store: '',
  },
];

module.exports = { defaultRoles, superAdminDefaultPermission };
